apiVersion: v1
kind: Namespace
metadata:
  name: utility
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: just-another-kahoot-bot
  namespace: utility
spec:
  replicas: 3
  selector:
    matchLabels:
      app: just-another-kahoot-bot
  template:
    metadata:
      labels:
        app: just-another-kahoot-bot
    spec:
      nodeSelector:
        kubernetes.io/hostname: homelab-0  # Ensure this runs only on homelab-1 node
      containers:
        - name: just-another-kahoot-bot
          image: feelfeel200088/just_another_kahoot_bot
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "8Gi"  # Limit memory to Gi
              cpu: "1"        # Limit CPU to 1 core
---
apiVersion: v1
kind: Service
metadata:
  name: just-another-kahoot-bot-external
  namespace: utility
spec:
  selector:
    app: just-another-kahoot-bot
  ports:
    - protocol: TCP
      port: 8000       # External port
      targetPort: 8000  # Container port
      nodePort: 30005    # Expose on NodePort 30005
  type: NodePort  # Exposes the service externally
---
apiVersion: v1
kind: Service
metadata:
  name: just-another-kahoot-bot-internal
  namespace: utility
spec:
  selector:
    app: just-another-kahoot-bot
  ports:
    - protocol: TCP
      port: 8000       # Internal port
      targetPort: 8000  # Target port on the pod
  type: ClusterIP  # Internal-only service
